--- #YAML:1.0
name:               MonitisMonitorManager
version:            3.6
abstract:           Monitis Monitor Manager (M3)
author:
    - Dan Fruehauf <malkodan@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    1:  ~
requires:
    1:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
